pipeline {
  agent {
    label 'Liferay Remote' 
  }
  environment {
	VALIDATION_FILE = "${WORKSPACE}/validations/validation_${BUILD_NUMBER}.txt"
	VALIDATION_FOLDER = "${WORKSPACE}/validations"
  }
  stages {
     stage('LIF_Download') { // for display purposes
		steps {
				checkout([$class: 'GitSCM', branches: [[name: 'develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'GitlabUserPass', url: '$URL_GIT']]])
				git branch: '$BRANCH', credentialsId: 'GitlabUserPass', url: '$URL_GIT'
			}
	}
	stage('Stage_Compile') {
		steps {
		parallel( modules:{
			echo 'gradle build'
			sh '''cd workspace/modules
			gradle build'''
		},theme:{
			echo 'theme'
			sh '''cd workspace/themes/orange-theme
            gulp build''' 
		},layouts:{
			echo 'layouts'
			sh '''cd workspace/themes/
			for d in *-layouttpl/ ; do
				cd $d
				echo "Compilando $d"
				gulp build
				cd ..
			done'''
		}
		)}
	}
    stage('Stage_QUALITY') {
			steps {
			parallel( unitTest:{
				echo 'unitTest'
				sh ''' cd workspace/modules
				gradle test '''	
			},sonar:{
				echo 'sonar'
				sh ''' JAVA_HOME=/home/jslavsoe/java/jdk1.8.0_101
				cd workspace
				gradle --info sonarqube 
				'''
			},qa:{
				echo 'qa'
				sh ''' cd workspace/modules
				gradle check '''
			}
			)}
	}
    stage('LIF_Upload_Artifactory') {
		steps {
			sh '''
			cd workspace
			gradle uploadArchives -x downloadNode -x npmInstall -x gulpBuild
			'''
		}
	}
  }
}