pipeline {
  agent {
    label 'Liferay Remote' 
  }
  environment {
	VALIDATION_FILE = "${WORKSPACE}/validations/validation_${BUILD_NUMBER}.txt"
	VALIDATION_FOLDER = "${WORKSPACE}/validations"
  }
  stages {
     stage('LIF_Download') { // for display purposes
		steps {
		echo "Param SKIPT_UNIT_TESTS is ${SKIPT_UNIT_TESTS}"
				if(SKIPT_UNIT_TESTS=='true'){
					echo "Param SKIPT_UNIT_TESTS is true"
				}else{
					echo "Param SKIPT_UNIT_TESTS is false"
				}
			}
	   post {
			success {
				writeFile(file: "${VALIDATION_FILE}", text: 'Download: SUCCESS \n')
			}
			failure {
				writeFile(file: "${VALIDATION_FILE}", text: 'Download: FAILURE \n')
				jiraComment body: "There is a problem on LIF_Download Repository step in $JOB_NAME build process", issueKey: "${ISSUE_KEY}"
			}

	   }
	}
  }
}